### ISSUE TITLE
Default file locations for saved inference samples

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#89]
Why:
  Minimize amount of user configuration steps.

How:
  Use natural pipeline hierarchy: pipeline name, element name, user specified optional subdir suffix
  Example:

  config:
```yaml
    - entry_area_watch:
         - object_detection:
         - save_samples:
             - subdir: objects
```
resulting dir:

```
/workspace/data/detections/entry_area_watch/objects/
```

**Comment by ivelin** [comment]
The implemented solution creates a sub-directory under the configured data dir for each save element using an UUID and timestamp. The resulting config looks like this:

```yaml
# path to the data directory
data_dir: &data_dir ./data

pipelines:
  # sequence of piped operations for use in daytime front door watch
   front_door_watch:
     - source: *src_recorded_cam_feed
     - detect_objects: # run ai inference on the input data
        <<: *tfm_image_detection
        confidence_threshold: 0.8
     - save_detections: # save samples from the inference results
        positive_interval: 2 # how often (in seconds) to save samples with ANY results above the confidence threshold
        idle_interval: 6000 # how often (in seconds) to save samples with NO results above the confidence threshold
     - detect_faces: # run ai inference on the samples from the previous element output
        <<: *tfm_face_detection
        confidence_threshold: 0.8
     - save_detections: # save samples from the inference results
        positive_interval: 2
        idle_interval: 600
```

Notice that individual `save_detections` elements do not specify output directory. The auto named dir structure looks like this:

```sh
pi@hass:/opt/ambianic-edge $ ls -al data/detections/
total 104
drwxr-xr-x 16 root root  4096 Nov  5 16:32 .
drwxr-xr-x  3 pi   pi    4096 Nov  8 08:38 ..
drwxr-xr-x  2 root root  4096 Nov  5 15:40 20191105-214000.841218
drwxr-xr-x  2 root root  4096 Nov  5 15:40 20191105-214001.017077
drwxr-xr-x  2 root root  4096 Nov  5 15:40 20191105-214001.063512
drwxr-xr-x  2 root root  4096 Nov  5 15:40 20191105-214001.107182

pi@hass:/opt/ambianic-edge $ ls -al data/detections/20191105-214001.063512/
total 476
drwxr-xr-x  2 root root   4096 Nov  5 15:40 .
drwxr-xr-x 16 root root   4096 Nov  5 16:32 ..
-rw-r--r--  1 root root 471468 Nov  5 15:40 20191105-214004.335555.jpg
-rw-r--r--  1 root root    349 Nov  5 15:40 20191105-214004.335555.json
```
